#Cổng kết nối
server:
  port: 8080
  servlet:
    context-path: /pharmacy
#Kết nối MySQL Server
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/pharmacy"
    username: root
    password: kieuduyen20112000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true


