#Cổng kết nối
server:
  port: 8080
  servlet:
    context-path: /api/v1/pharmacy

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/pharmacy"
    username: root
    password: kieuduyen20112000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: pharmacywebsite4@gmail.com
    password: lzod fxlq depg tovs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

outbound:
  identity:
    client-id: "1061151903576-nn2026pco5803tqgui1k65hf4cp9a8ii.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://localhost:3000/authenticate"

jwt:
  signerKey: "0HOHKN7jKVL8N7isueYCYmNqqytQj/rrjnQOzD4R971R1u6357OvxgJ5u/MFF8/u"
  valid-duration: 3600 #in seconds
  refreshable-duration: 36000 #in seconds