#Cổng kết nối
server:
  port: 8080
  servlet:
    context-path: /pharmacy
#Kết nối MySQL Server
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/pharmacy"
    username: root
    password: kieuduyen20112000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

outbound:
  identity:
    client-id: "682283271944-9a4s4hhnik8tqarogeqapqtu6qmatn67.apps.googleusercontent.com"
    client-secret: "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"
    redirect-uri: "http://localhost:3000/authenticate"
jwt:
  signerKey: "0HOHKN7jKVL8N7isueYCYmNqqytQj/rrjnQOzD4R971R1u6357OvxgJ5u/MFF8/u"


